set(EDUKE32_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})

add_subdirectory(audiolib)
add_subdirectory(build)
add_subdirectory(duke3d)
add_subdirectory(glad)
add_subdirectory(imgui)
add_subdirectory(kenbuild)
add_subdirectory(libxmp-lite)
add_subdirectory(mact)
add_subdirectory(mimalloc)
add_subdirectory(sw)
# add_subdirectory(tools)
# add_subdirectory(voidwrap)
